# Generated by Django 2.0.5 on 2018-05-15 08:50

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', DjangoUeditor.models.UEditorField(blank=True, default='test', verbose_name='write your content')),
            ],
        ),
    ]
