# Generated by Django 2.0.5 on 2018-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='ResourcePwd',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='articles',
            name='ResourceUrl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
