# Generated by Django 2.0.5 on 2018-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmspace', '0002_auto_20180515_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Cover',
            field=models.ImageField(default='static/images/logo.png', upload_to='upload/'),
        ),
    ]
