# Generated by Django 2.0.2 on 2018-05-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmspace', '0003_articles_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Cover',
            field=models.ImageField(default='photo.jpg', upload_to='image/%Y/%m/%d'),
        ),
    ]
